# Generated by Django 6.0.3 on 2026-03-31 01:56

import gestion.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(help_text='Ingrese solo los dígitos del número telefónico.', max_length=20, validators=[gestion.validators.validar_solo_numeros]),
        ),
        migrations.AlterField(
            model_name='ordenreparacion',
            name='costo_estimado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[gestion.validators.validar_costo]),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='anio',
            field=models.IntegerField(validators=[gestion.validators.validar_anio_no_futuro], verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='patente',
            field=models.CharField(max_length=15, unique=True, validators=[gestion.validators.validar_formato_placa], verbose_name='Placa'),
        ),
    ]
